### ISSUE TITLE
Possible typo in env variable

### ISSUE THREAD

**Issue by StefanCenusa** [chartmuseum/ui#30]
CHART_MUSESUM_URL is "musesum" a typo of "museum"?

https://github.com/chartmuseum/ui/blob/2355c40d8f980c77446e3be2ab76efcdd8456c92/controllers/chartmuseum.go#L64

It looks very confusing.

Thanks!

**Comment by Mistawes** [comment]
Just updated this typo and rebuilt chartmuseum-ui, worked fine! Previously it was always trying to check localhost/api/charts as the env var wasn't being found (obviously!). FWIW: I'm reaching chartmuseum via AWS ALB, not locally.

I also adjusted "CHART_MUSEUM_API_GET_CHARTS" in that same file (just a few lines up).

This should really be fixed..
